name: ArtisanROM-S20+

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: UbuntuWSL-16GB-16C-2048GB
    steps:
      - name: Install the build packages
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick protobuf-compiler python3-protobuf lib32readline-dev lib32z1-dev libdw-dev libelf-dev lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

      - name: Initialize the ArtisanROM source repository
        run: |
          cd /mnt/d/android/lineage
          repo init -u https://github.com/ArtisanROM/android.git -b lineage-21.0 --git-lfs

      - name: Prepare the device-specific code
        run: |
          cd /mnt/d/android/lineage
          mkdir -p .repo/local_manifests
          curl -o .repo/local_manifests/roomservice.xml https://raw.githubusercontent.com/Android-Artisan/LineageOS/refs/heads/main/manifest/roomservice-S20x.xml
          repo sync --force-sync
          source build/envsetup.sh
      
      - name: Configure git
        run: |
          git config --global user.email romartisan2025@gmail.com
          git config --global user.name Artisan
      
      - name: Build ArtisanROM
        run: |
          cd /mnt/d/android/lineage
          source build/envsetup.sh
          brunch y2s

      - name: Upload ArtisanROM to GitHub Nightly Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /mnt/d/android/lineage/out/target/product/y2s/recovery.img
            /mnt/d/android/lineage/out/target/product/y2s/lineage-21.0-*-UNOFFICIAL-y2s.zip
          name: ArtisanROM-nightly-S20+-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: ArtisanROM-Nightly-S20+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
