name: LineageOS-z3q-WSL

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: UbuntuWSL-16GB-16C-2048GB
    steps:
      - name: Install the build packages
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick protobuf-compiler python3-protobuf lib32readline-dev lib32z1-dev libdw-dev libelf-dev lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
      
      - name: Configure git
        run: |
          git config --global user.email romartisan2025@gmail.com
          git config --global user.name Artisan
      
      - name: Initialize the LineageOS source repository
        run: |
          cd /mnt/wsl/PHYSICALDRIVE1/android/lineage
          sudo repo init -u https://github.com/ArtisanROM/android.git -b lineage-21.0 --git-lfs
          sudo repo sync --force-sync

      - name: Prepare the device-specific code
        run: |
          cd /mnt/wsl/PHYSICALDRIVE1/android/lineage
          mkdir -p .repo/local_manifests
          sudo curl -o .repo/local_manifests/roomservice.xml https://raw.githubusercontent.com/Android-Artisan/LineageOS/refs/heads/main/manifest/roomservice-S20x.xml
          source build/envsetup.sh
      
      - name: Start the build
        run: |
          cd /mnt/wsl/PHYSICALDRIVE1/android/lineage
          sudo repo sync --force-sync
          source build/envsetup.sh
          brunch z3q

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /mnt/wsl/PHYSICALDRIVE1/android/lineage/out/target/product/z3q/recovery.img
            /mnt/wsl/PHYSICALDRIVE1/android/lineage/out/target/product/z3q/lineage-21.0-*-UNOFFICIAL-z3q.zip
          name: ArtisanROM-nightly-z3q-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: ArtisanROM-Nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
